import_model: general_perf/model_zoo/regular/open_resnet50/resnet50-torch-fp32.onnx
export_model: general_perf/model_zoo/regular/open_resnet50/resnet50-torch-fp32_qdq.onnx
force_advance_quant: True
export_batch: -1

dataset:
  calib_dir: general_perf/datasets/open_imagenet/ILSVRC2012_img_val
  calib_num: 100
  batch_size: 4
  preprocessing:
    enable: true
    attributes:
      isreverse: False
      mean: [123.68, 116.78, 103.94]
      std: [58.4, 57.12, 57.37]
      resize:
        keep_ratio: False
        to: [3, 256, 256]
        centercrop: [224,224]
